### ISSUE TITLE
Support for abstract methods

### ISSUE THREAD

**Issue by Goobles** [cesarParra/apex-reflection#16]
It seems that the modifier keyword "abstract" isn't included in the MethodMirror.memberModifiers

The member modifiers enum doesn't include abstract either.

https://github.com/cesarParra/apex-reflection/blob/main/lib/src/model/modifiers.dart#L15

Can this information somehow be included in the result?
For now I'm working around it by adding an `@abstract true` apexdoc annotation and reading from there. I'm using this reflection info to generate a part of the IlluminatedCloud symbol table that includes documentation for managed package apex classes.

**Comment by cesarParra** [comment]
Yeah, that's a miss. Let me take a look into that

**Comment by cesarParra** [comment]
Fix should be available in version [2.7.1](https://github.com/cesarParra/apex-reflection/releases/tag/v2.7.1)
