### ISSUE TITLE
Type recognition: Iterable as generic and namespace references

### ISSUE THREAD

**Issue by WimTibackx** [cesarParra/apex-reflection#20]
Hi!
I noticed two type parsing issues that can occur especially around batchable classes. I'll first explain the result I'm seeing versus what I would expect, and at the end I've included a small example as well as the full current reflection output.

## Iterable as generic

I noticed that usages of Iterable don't generate a complex type.

- Given a method declaration with an Iterable return type:
    `public Iterable<String> start(Database.BatchableContext info) {}`
- The recognized result is a simple ReferenceObjectType
    `"typeReference": {"type": "Iterable<String>","rawDeclaration": "Iterable<String>"}`
- rather than a List/Set-like single param generic type:
    `"typeReference": {"type": "Iterable","rawDeclaration": "Iterable<String>", "ofType": {"type":"String", "rawDeclaration":"String"}}`

I'm guessing this is because how `type_references.dart::ObjectTypeReference` checks for List, Set, or Map elements; and else falls back to a plain type.

## Namespace references

I'm noticing that some fully qualified typenames (for example: Database.BatchableContext) get cut off at the namespace.

- Given this method declaration
    `public Iterable<String> start(Database.BatchableContext info) {}`
- The parameter is recognized as just "Database"
    `{"memberModifiers": [],"name": "info","typeReference": {"type": "Database","rawDeclaration": "Database"}}`
- rather than Database.Batchable:
    `{"memberModifiers": [],"name": "info","typeReference": {"type": "Database.BatchableContext","rawDeclaration": "Database.BatchableContext"}}`

I'm guessing here that this is because the fallback-rule in `type_references.dart::ObjectTypeReference` uses `typeRefContext.typeName(0)!.text` instead of `typeRefContext.text` thereby looking only at the first typeName and not at the optional extra `DOT typeName` elements in the typeRef declaration `typeName (DOT typeName)* arraySubscripts`. Haven't gotten around to setting up the toolchain myself yet, so I haven't been able to verify that this is the correct diagnosis or fix.

Complete example source: [batchable_example.txt](https://github.com/user-attachments/files/15967150/batchable_example.txt)
Complete parse result: [parse-result-v2_9_0.json](https://github.com/user-attachments/files/15967170/parse-result-v2_9_0.json)

**Comment by cesarParra** [comment]
Hi @WimTibackx 

Good finds, and thanks for the excellent level of detail!

I was able to replicate as well, let me take a look and put those fixes in place.

**Comment by cesarParra** [comment]
@WimTibackx Test it out with version `2.9.3` which I just released. Here is the updated JSON output for the same Apex input

```json
{
  "typeMirror": {
    "docComment": null,
    "access_modifier": "public",
    "annotations": [],
    "name": "RecalculateSomeAggregatedData",
    "group": null,
    "groupDescription": null,
    "type_name": "class",
    "methods": [
      {
        "docComment": null,
        "access_modifier": "public",
        "annotations": [],
        "name": "start",
        "group": null,
        "groupDescription": null,
        "memberModifiers": [],
        "typeReference": {
          "type": "Iterable",
          "rawDeclaration": "Iterable<String>",
          "ofType": {
            "type": "String",
            "rawDeclaration": "String"
          }
        },
        "parameters": [
          {
            "memberModifiers": [],
            "name": "info",
            "typeReference": {
              "type": "Database.BatchableContext",
              "rawDeclaration": "Database.BatchableContext"
            }
          }
        ]
      },
      {
        "docComment": null,
        "access_modifier": "public",
        "annotations": [],
        "name": "execute",
        "group": null,
        "groupDescription": null,
        "memberModifiers": [],
        "typeReference": {
          "type": "void",
          "rawDeclaration": "void"
        },
        "parameters": [
          {
            "memberModifiers": [],
            "name": "info",
            "typeReference": {
              "type": "Database.BatchableContext",
              "rawDeclaration": "Database.BatchableContext"
            }
          },
          {
            "memberModifiers": [],
            "name": "scope",
            "typeReference": {
              "type": "List",
              "rawDeclaration": "List<String>",
              "ofType": {
                "type": "String",
                "rawDeclaration": "String"
              }
            }
          }
        ]
      },
      {
        "docComment": null,
        "access_modifier": "public",
        "annotations": [],
        "name": "finish",
        "group": null,
        "groupDescription": null,
        "memberModifiers": [],
        "typeReference": {
          "type": "void",
          "rawDeclaration": "void"
        },
        "parameters": [
          {
            "memberModifiers": [],
            "name": "info",
            "typeReference": {
              "type": "Database.BatchableContext",
              "rawDeclaration": "Database.BatchableContext"
            }
          }
        ]
      }
    ],
    "sharingModifier": null,
    "classModifier": null,
    "extended_class": null,
    "implemented_interfaces": [
      "Database.Batchable<Account>"
    ],
    "properties": [],
    "fields": [],
    "constructors": [],
    "enums": [],
    "interfaces": [],
    "classes": []
  },
  "error": null
}
```

**Comment by WimTibackx** [comment]
Hi @cesarParra, I can confirm that version 2.9.3 fixes these issues for me. Thanks for the quick turnaround on this!
